import '../../../domain/entities/customer.dart';

/// Static customer seed — a 1:1 port of the prototype's `customersRaw` array.
/// The ONLY place customer sample data lives. To integrate the API, replace
/// this class with a remote data source returning `List<Customer>`.
class CustomersMockDataSource {
  const CustomersMockDataSource();

  List<Customer> fetchCustomers() => const [
        Customer(id: 'C2001', leadId: 'L1001', name: 'Ramesh Pillai', initials: 'RP', company: 'Kalyan Silks', project: 'Showroom interiors', value: '₹18L', valueNum: 1800000, status: 'upsell', since: 'Dec 2025', statusDays: 12, score: 70, source: 'Referral', owner: 'am', team: ['am'], phone: '+91 94100 11000', email: 'ramesh@kalyansilks.in', website: 'www.kalyansilks.in', industry: 'Retail', location: 'Thrissur', createdOn: '08 Dec 2025', time: '2h ago', lastFu: 'Call · 2h ago', notif: 1),
        Customer(id: 'C2002', leadId: 'L1002', name: 'Aboobacker Haji', initials: 'AH', company: 'Lulu Fashion Store', project: 'Flagship store fit-out', value: '₹36.5L', valueNum: 3650000, status: 'active', since: 'Dec 2025', statusDays: 25, score: 71, source: 'Website', owner: 'rk', team: ['rk', 'me'], phone: '+91 484 405 8890', email: 'aboobacker@lulufashion.in', website: 'www.lulufashion.in', industry: 'Retail', location: 'Edappally', createdOn: '22 Dec 2025', time: '5h ago', lastFu: 'Email · 5h ago', notif: 0),
        Customer(id: 'C2003', leadId: 'L1003', name: 'Jose Kuriakose', initials: 'JK', company: 'Marari Sands Resort', project: 'Resort villa interiors', value: '₹55L', valueNum: 5500000, status: 'active', since: 'Jan 2026', statusDays: 40, score: 72, source: 'LinkedIn', owner: 'fa', team: ['fa', 'me', 'an'], phone: '+91 478 286 2345', email: 'jose@mararisands.in', website: 'www.mararisands.in', industry: 'Hospitality', location: 'Alappuzha', createdOn: '14 Jan 2026', time: 'Yesterday', lastFu: 'Meeting · Yesterday', notif: 0),
        Customer(id: 'C2004', leadId: 'L1004', name: 'Nikhil Menon', initials: 'NM', company: 'Taj Gateway Annexe', project: 'Banquet & lounge refit', value: '₹73.5L', valueNum: 7350000, status: 'active', since: 'Jan 2026', statusDays: 51, score: 73, source: 'Google Ads', owner: 'dr', team: ['dr'], phone: '+91 484 667 1234', email: 'nikhil.menon@tajhotels.com', website: 'www.tajhotels.com', industry: 'Hospitality', location: 'Ernakulam', createdOn: '28 Jan 2026', time: '1d ago', lastFu: 'Site visit · 1d ago', notif: 0),
        Customer(id: 'C2005', leadId: 'L1005', name: 'Priya Varma', initials: 'PV', company: 'Aster Medcity OPD', project: 'Multi-speciality OPD', value: '₹92L', valueNum: 9200000, status: 'completed', since: 'Feb 2026', statusDays: 8, score: 74, source: 'Trade show', owner: 'st', team: ['st', 'me'], phone: '+91 484 669 9000', email: 'priya.varma@asterdm.com', website: 'www.asterdmhealthcare.com', industry: 'Healthcare', location: 'Kochi', createdOn: '09 Feb 2026', time: '2d ago', lastFu: 'Form fill · 2d ago', notif: 0),
        Customer(id: 'C2006', leadId: 'L1006', name: 'Suresh Nair', initials: 'SN', company: 'KIMS Clinic', project: 'OPD + waiting areas', value: '₹1.10Cr', valueNum: 11000000, status: 'active', since: 'Feb 2026', statusDays: 33, score: 75, source: 'Cold call', owner: 'an', team: ['an', 'me', 'fa'], phone: '+91 471 294 1000', email: 'suresh.nair@kimshealth.org', website: 'www.kimshealth.org', industry: 'Healthcare', location: 'Trivandrum', createdOn: '20 Feb 2026', time: '3d ago', lastFu: 'Call · 3d ago', notif: 2),
        Customer(id: 'C2007', leadId: 'L1007', name: 'Biju Thomas', initials: 'BT', company: 'Federal Bank Aluva', project: 'Workspace fit-out · 80 seats', value: '₹1.29Cr', valueNum: 12900000, status: 'active', since: 'Mar 2026', statusDays: 19, score: 76, source: 'Referral', owner: 'am', team: ['am'], phone: '+91 484 262 3333', email: 'biju.thomas@federalbank.in', website: 'www.federalbank.co.in', industry: 'BFSI', location: 'Aluva', createdOn: '02 Mar 2026', time: '4d ago', lastFu: 'Email · 4d ago', notif: 0),
        Customer(id: 'C2008', leadId: 'L1008', name: 'Anand Krishnan', initials: 'AK', company: 'Infopark Tower B', project: 'HQ refresh + cabins', value: '₹1.48Cr', valueNum: 14800000, status: 'active', since: 'Mar 2026', statusDays: 14, score: 77, source: 'Website', owner: 'rk', team: ['rk', 'me'], phone: '+91 484 415 4000', email: 'anand.k@infopark.in', website: 'www.infopark.in', industry: 'IT / ITES', location: 'Kakkanad', createdOn: '15 Mar 2026', time: '6d ago', lastFu: 'Meeting · 6d ago', notif: 0),
        Customer(id: 'C2009', leadId: 'L1009', name: 'Geetha Mohan', initials: 'GM', company: 'Technopark Tejaswini', project: 'Branch interiors + signage', value: '₹1.66Cr', valueNum: 16600000, status: 'upsell', since: 'Mar 2026', statusDays: 6, score: 78, source: 'LinkedIn', owner: 'fa', team: ['fa', 'me', 'an'], phone: '+91 471 700 2700', email: 'geetha.m@technopark.org', website: 'www.technopark.org', industry: 'IT / ITES', location: 'Trivandrum', createdOn: '27 Mar 2026', time: '1w ago', lastFu: 'Site visit · 1w ago', notif: 0),
        Customer(id: 'C2010', leadId: null, name: 'Ashraf Ali', initials: 'AA', company: 'Malabar Gold Showroom', project: 'Showroom expansion', value: '₹2.03Cr', valueNum: 20300000, status: 'active', since: 'Apr 2026', statusDays: 62, score: 69, source: 'Referral', owner: 'st', team: ['st'], phone: '+91 495 272 2255', email: 'ashraf@malabargold.com', website: 'www.malabargold.com', industry: 'Retail', location: 'Kozhikode', createdOn: '02 Apr 2026', time: '2d ago', lastFu: 'Meeting · 2d ago', notif: 0),
        Customer(id: 'C2011', leadId: null, name: 'Mathew George', initials: 'MG', company: 'Nirapara Supermarket', project: 'Store renovation', value: '₹55L', valueNum: 5500000, status: 'active', since: 'May 2026', statusDays: 30, score: 66, source: 'Google Ads', owner: 'an', team: ['an'], phone: '+91 481 256 7890', email: 'mathew@nirapara.com', website: 'www.nirapara.com', industry: 'Retail', location: 'Kottayam', createdOn: '05 May 2026', time: '1d ago', lastFu: 'Site visit · 1d ago', notif: 0),
        Customer(id: 'C2012', leadId: null, name: 'Devika Iyer', initials: 'DI', company: 'Paragon Restaurant', project: 'Dining hall interiors', value: '₹18L', valueNum: 1800000, status: 'completed', since: 'Apr 2026', statusDays: 20, score: 73, source: 'Referral', owner: 'dr', team: ['dr'], phone: '+91 495 276 1020', email: 'devika@paragonrestaurant.in', website: 'www.paragonrestaurant.in', industry: 'Hospitality', location: 'Kozhikode', createdOn: '18 Apr 2026', time: '5d ago', lastFu: 'Call · 5d ago', notif: 0),
        Customer(id: 'C2013', leadId: null, name: 'Hari Prasad', initials: 'HP', company: 'Orbit Health', project: 'Clinic chain refresh', value: '₹22L', valueNum: 2200000, status: 'lost', since: 'Feb 2026', statusDays: 44, score: 35, source: 'Cold call', owner: 'rk', team: ['rk'], phone: '+91 484 240 5566', email: 'hari@orbithealth.in', website: 'www.orbithealth.in', industry: 'Healthcare', location: 'Kochi', createdOn: '10 Feb 2026', time: '3w ago', lastFu: 'Call · 3w ago', notif: 0),
      ];
}
