import '../../../domain/entities/lead.dart';

/// Static lead seed — a 1:1 port of the prototype's `raw` array. This is the
/// ONLY place lead sample data lives. To integrate the API, replace this class
/// with a remote data source returning `List<Lead>`; nothing else changes.
class LeadsMockDataSource {
  const LeadsMockDataSource();

  List<Lead> fetchLeads() => const [
        Lead(id: 'L1001', name: 'Ramesh Pillai', initials: 'RP', company: 'Kalyan Silks', project: 'Showroom interiors', value: '₹18L', valueNum: 1800000, status: 'won', statusDays: 0, score: 100, source: 'Referral', owner: 'am', team: ['am'], phone: '+91 94100 11000', email: 'ramesh@kalyansilks.in', website: 'www.kalyansilks.in', industry: 'Retail', location: 'Thrissur', createdOn: '08 Dec 2025', time: '2h ago', lastFu: 'Call · 2h ago', notif: 2),
        Lead(id: 'L1002', name: 'Aboobacker Haji', initials: 'AH', company: 'Lulu Fashion Store', project: 'Flagship store fit-out', value: '₹36.5L', valueNum: 3650000, status: 'negotiation', statusDays: 19, score: 77, source: 'Website', owner: 'rk', team: ['rk', 'me'], phone: '+91 484 405 8890', email: 'aboobacker@lulufashion.in', website: 'www.lulufashion.in', industry: 'Retail', location: 'Edappally', createdOn: '22 Dec 2025', time: '5h ago', lastFu: 'Email · 5h ago', notif: 1),
        Lead(id: 'L1003', name: 'Jose Kuriakose', initials: 'JK', company: 'Marari Sands Resort', project: 'Resort villa interiors', value: '₹55L', valueNum: 5500000, status: 'won', statusDays: 0, score: 100, source: 'LinkedIn', owner: 'fa', team: ['fa', 'me', 'an'], phone: '+91 478 286 2345', email: 'jose@mararisands.in', website: 'www.mararisands.in', industry: 'Hospitality', location: 'Alappuzha', createdOn: '14 Jan 2026', time: 'Yesterday', lastFu: 'Meeting · Yesterday', notif: 0),
        Lead(id: 'L1004', name: 'Nikhil Menon', initials: 'NM', company: 'Taj Gateway Annexe', project: 'Banquet & lounge refit', value: '₹73.5L', valueNum: 7350000, status: 'qualified', statusDays: 13, score: 63, source: 'Google Ads', owner: 'dr', team: ['dr', 'me', 'st', 'an'], phone: '+91 484 667 1234', email: 'nikhil.menon@tajhotels.com', website: 'www.tajhotels.com', industry: 'Hospitality', location: 'Ernakulam', createdOn: '28 Jan 2026', time: '1d ago', lastFu: 'Site visit · 1d ago', notif: 3),
        Lead(id: 'L1005', name: 'Priya Varma', initials: 'PV', company: 'Aster Medcity OPD', project: 'Multi-speciality OPD', value: '₹92L', valueNum: 9200000, status: 'won', statusDays: 0, score: 100, source: 'Trade show', owner: 'st', team: ['st'], phone: '+91 484 669 9000', email: 'priya.varma@asterdm.com', website: 'www.asterdmhealthcare.com', industry: 'Healthcare', location: 'Kochi', createdOn: '09 Feb 2026', time: '2d ago', lastFu: 'Form fill · 2d ago', notif: 0),
        Lead(id: 'L1006', name: 'Suresh Nair', initials: 'SN', company: 'KIMS Clinic', project: 'OPD + waiting areas', value: '₹1.10Cr', valueNum: 11000000, status: 'negotiation', statusDays: 23, score: 81, source: 'Cold call', owner: 'an', team: ['an', 'me'], phone: '+91 471 294 1000', email: 'suresh.nair@kimshealth.org', website: 'www.kimshealth.org', industry: 'Healthcare', location: 'Trivandrum', createdOn: '20 Feb 2026', time: '3d ago', lastFu: 'Call · 3d ago', notif: 4),
        Lead(id: 'L1007', name: 'Biju Thomas', initials: 'BT', company: 'Federal Bank Aluva', project: 'Workspace fit-out · 80 seats', value: '₹1.29Cr', valueNum: 12900000, status: 'won', statusDays: 0, score: 100, source: 'Referral', owner: 'am', team: ['am', 'me', 'rk'], phone: '+91 484 262 3333', email: 'biju.thomas@federalbank.in', website: 'www.federalbank.co.in', industry: 'BFSI', location: 'Aluva', createdOn: '02 Mar 2026', time: '4d ago', lastFu: 'Email · 4d ago', notif: 0),
        Lead(id: 'L1008', name: 'Anand Krishnan', initials: 'AK', company: 'Infopark Tower B', project: 'HQ refresh + cabins', value: '₹1.48Cr', valueNum: 14800000, status: 'qualified', statusDays: 17, score: 67, source: 'Website', owner: 'rk', team: ['rk', 'me', 'dr', 'st'], phone: '+91 484 415 4000', email: 'anand.k@infopark.in', website: 'www.infopark.in', industry: 'IT / ITES', location: 'Kakkanad', createdOn: '15 Mar 2026', time: '6d ago', lastFu: 'Meeting · 6d ago', notif: 1),
        Lead(id: 'L1009', name: 'Geetha Mohan', initials: 'GM', company: 'Technopark Tejaswini', project: 'Branch interiors + signage', value: '₹1.66Cr', valueNum: 16600000, status: 'negotiation', statusDays: 26, score: 84, source: 'LinkedIn', owner: 'fa', team: ['fa'], phone: '+91 471 700 2700', email: 'geetha.m@technopark.org', website: 'www.technopark.org', industry: 'IT / ITES', location: 'Trivandrum', createdOn: '27 Mar 2026', time: '1w ago', lastFu: 'Site visit · 1w ago', notif: 0),
        Lead(id: 'L1010', name: 'Sangeeth Raj', initials: 'SR', company: 'Workafella Coworking', project: 'Coworking floor refit', value: '₹42L', valueNum: 4200000, status: 'new', statusDays: 2, score: 58, source: 'Website', owner: 'dr', team: ['dr', 'me'], phone: '+91 422 450 8800', email: 'sangeeth@workafella.com', website: 'www.workafella.com', industry: 'Co-working', location: 'Kochi', createdOn: '28 Jun 2026', time: '2d ago', lastFu: 'Email · 2d ago', notif: 1),
        Lead(id: 'L1011', name: 'Mathew George', initials: 'MG', company: 'Nirapara Supermarket', project: 'Store renovation', value: '₹27L', valueNum: 2700000, status: 'new', statusDays: 1, score: 44, source: 'Google Ads', owner: 'am', team: ['am'], phone: '+91 481 256 7890', email: 'mathew@nirapara.com', website: 'www.nirapara.com', industry: 'Retail', location: 'Kottayam', createdOn: '02 Jul 2026', time: '1d ago', lastFu: 'Call · 1d ago', notif: 0),
        Lead(id: 'L1012', name: 'Ashraf Ali', initials: 'AA', company: 'Malabar Gold Showroom', project: 'Showroom expansion', value: '₹2.03Cr', valueNum: 20300000, status: 'new', statusDays: 0, score: 51, source: 'Referral', owner: 'st', team: ['st', 'me'], phone: '+91 495 272 2255', email: 'ashraf@malabargold.com', website: 'www.malabargold.com', industry: 'Retail', location: 'Kozhikode', createdOn: '05 Jul 2026', time: '4h ago', lastFu: 'Created · 4h ago', notif: 2),
        Lead(id: 'L1013', name: 'Vinod Kumar', initials: 'VK', company: 'Toms Auto Hyundai', project: 'Showroom + service lounge', value: '₹95L', valueNum: 9500000, status: 'new', statusDays: 3, score: 39, source: 'Cold call', owner: 'rk', team: ['rk'], phone: '+91 487 238 4455', email: 'vinod@tomsauto.in', website: 'www.tomshyundai.com', industry: 'Automotive', location: 'Thrissur', createdOn: '25 Jun 2026', time: '3d ago', lastFu: 'Call · 3d ago', notif: 0),
        Lead(id: 'L0996', name: 'Tomin Chacko', initials: 'TC', company: 'Vintage Cafe', project: 'Cafe interior', value: '₹8L', valueNum: 800000, status: 'lost', statusDays: 41, score: 22, source: 'Website', owner: 'dr', team: ['dr'], phone: '+91 484 231 9080', email: 'tomin@vintagecafe.in', website: '—', industry: 'Hospitality', location: 'Fort Kochi', createdOn: '18 Apr 2026', time: '3w ago', lastFu: 'Call · 3w ago', notif: 0),
        Lead(id: 'L0991', name: 'Dr. Priya Das', initials: 'PD', company: 'City Hospital', project: 'Reception refresh', value: '₹6.5L', valueNum: 650000, status: 'archived', statusDays: 74, score: 18, source: 'Website', owner: 'an', team: ['an'], phone: '+91 471 233 8899', email: 'priya.das@cityhospital.in', website: 'www.cityhospital.in', industry: 'Healthcare', location: 'Trivandrum', createdOn: '02 Feb 2026', time: '2mo ago', lastFu: 'Email · 2mo ago', notif: 0),
        Lead(id: 'L0990', name: 'Hariharan B', initials: 'HB', company: 'Green Villa Homestay', project: 'Homestay refurb', value: '₹5L', valueNum: 500000, status: 'archived', statusDays: 89, score: 15, source: 'Trade show', owner: 'fa', team: ['fa'], phone: '+91 481 245 6677', email: 'stay@greenvilla.in', website: '—', industry: 'Hospitality', location: 'Kumarakom', createdOn: '12 Jan 2026', time: '3mo ago', lastFu: '—', notif: 0),
      ];
}
