import '../../../domain/entities/quote.dart';

/// Static quote seed — a 1:1 port of the prototype's `quotes` array. This is the
/// ONLY place quote sample data lives. To integrate the API, replace this class
/// with a remote data source returning `List<Quote>`; nothing else changes.
class QuotesMockDataSource {
  const QuotesMockDataSource();

  List<Quote> fetchQuotes() => const [
        Quote(id: 'Q2052', custId: 'C2001', leadId: null, status: 'sent', amount: '₹9L', amountNum: 900000, issued: '15 Jun 2026', valid: '15 Jul 2026', template: 'Standard', payType: 'Lump sum', currency: 'INR', dueDate: '—', owner: 'am', items: [QuoteItem(name: 'Loose furniture package', qty: 1, rate: '₹9L', amt: '₹9L')], note: 'Sent to client with a 14-day validity. Follow up if no response by Friday.'),
        Quote(id: 'Q2051', custId: 'C2001', leadId: null, status: 'accepted', amount: '₹38L', amountNum: 3800000, issued: '28 May 2026', valid: '10 Jul 2026', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '10 Jul 2026', owner: 'am', items: [QuoteItem(name: 'Boutique wing fit-out', qty: 1, rate: '₹32L', amt: '₹32L'), QuoteItem(name: 'Accent lighting package', qty: 1, rate: '₹6L', amt: '₹6L')], note: 'Client approved over call; PO expected this week.'),
        Quote(id: 'Q2050', custId: 'C2001', leadId: null, status: 'expired', amount: '₹2.5L', amountNum: 250000, issued: '02 May 2026', valid: '02 Jun 2026', template: 'Compact', payType: 'Lump sum', currency: 'INR', dueDate: '—', owner: 'am', items: [QuoteItem(name: 'Lighting rework — trial floor', qty: 1, rate: '₹2.5L', amt: '₹2.5L')], note: null),
        Quote(id: 'Q2049', custId: 'C2003', leadId: null, status: 'accepted', amount: '₹42L', amountNum: 4200000, issued: '20 Mar 2026', valid: '28 Mar 2026', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '28 Mar 2026', owner: 'fa', items: [QuoteItem(name: 'Villa block A interiors', qty: 4, rate: '₹10.5L', amt: '₹42L')], note: null),
        Quote(id: 'Q2001', custId: 'C2001', leadId: null, status: 'accepted', amount: '₹18L', amountNum: 1800000, issued: '05 Apr 2026', valid: '12 Apr 2026', template: 'Standard', payType: 'Lump sum', currency: 'INR', dueDate: '12 Apr 2026', owner: 'am', items: [QuoteItem(name: 'Showroom interiors — ground floor', qty: 1, rate: '₹18L', amt: '₹18L')], note: 'Source quote for INV-3001.'),
        Quote(id: 'Q2002', custId: 'C2002', leadId: null, status: 'expired', amount: '₹58.9L', amountNum: 5890000, issued: '28 Mar 2026', valid: '28 Apr 2026', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '—', owner: 'rk', items: [QuoteItem(name: 'Store fit-out — phase 1', qty: 1, rate: '₹38L', amt: '₹38L'), QuoteItem(name: 'MEP & HVAC works', qty: 1, rate: '₹14.9L', amt: '₹14.9L'), QuoteItem(name: 'Signage package', qty: 1, rate: '₹6L', amt: '₹6L')], note: null),
        Quote(id: 'Q2003', custId: 'C2003', leadId: null, status: 'accepted', amount: '₹55L', amountNum: 5500000, issued: '25 Apr 2026', valid: '09 May 2026', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '09 May 2026', owner: 'fa', items: [QuoteItem(name: 'Villa interiors — beach row', qty: 1, rate: '₹40L', amt: '₹40L'), QuoteItem(name: 'Outdoor deck & pergola', qty: 1, rate: '₹15L', amt: '₹15L')], note: 'Source quote for INV-3002.'),
        Quote(id: 'Q2004', custId: 'C2004', leadId: null, status: 'expired', amount: '₹85.7L', amountNum: 8570000, issued: '22 Apr 2026', valid: '22 May 2026', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '—', owner: 'dr', items: [QuoteItem(name: 'Banquet hall refit', qty: 1, rate: '₹58L', amt: '₹58L'), QuoteItem(name: 'Lounge & bar interiors', qty: 1, rate: '₹19.7L', amt: '₹19.7L'), QuoteItem(name: 'Acoustic treatment', qty: 1, rate: '₹8L', amt: '₹8L')], note: null),
        Quote(id: 'Q2005', custId: 'C2005', leadId: null, status: 'accepted', amount: '₹92L', amountNum: 9200000, issued: '20 May 2026', valid: '04 Jun 2026', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '04 Jun 2026', owner: 'st', items: [QuoteItem(name: 'OPD interiors — level 2', qty: 1, rate: '₹64L', amt: '₹64L'), QuoteItem(name: 'Modular consultation rooms', qty: 8, rate: '₹3.5L', amt: '₹28L')], note: 'Source quote for INV-3003.'),
        Quote(id: 'Q2006', custId: 'C2006', leadId: null, status: 'rejected', amount: '₹35.2L', amountNum: 3520000, issued: '30 May 2026', valid: '15 Jun 2026', template: 'Compact', payType: 'Lump sum', currency: 'INR', dueDate: '—', owner: 'an', items: [QuoteItem(name: 'Waiting area refresh', qty: 1, rate: '₹22L', amt: '₹22L'), QuoteItem(name: 'Reception joinery', qty: 1, rate: '₹13.2L', amt: '₹13.2L')], note: 'Client asked to rework scope — budget cap ₹30L.'),
        Quote(id: 'Q2007', custId: 'C2007', leadId: null, status: 'accepted', amount: '₹1.29Cr', amountNum: 12900000, issued: '10 Jun 2026', valid: '24 Jun 2026', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '24 Jun 2026', owner: 'am', items: [QuoteItem(name: 'Workspace fit-out — 80 seats', qty: 1, rate: '₹98L', amt: '₹98L'), QuoteItem(name: 'Cabins & meeting rooms', qty: 1, rate: '₹31L', amt: '₹31L')], note: 'Source quote for INV-3004.'),
        Quote(id: 'Q2008', custId: 'C2008', leadId: null, status: 'sent', amount: '₹91.5L', amountNum: 9150000, issued: '26 Jun 2026', valid: '30 Jul 2026', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '—', owner: 'rk', items: [QuoteItem(name: 'HQ refresh — floors 3-5', qty: 1, rate: '₹74L', amt: '₹74L'), QuoteItem(name: 'Director cabins', qty: 5, rate: '₹3.5L', amt: '₹17.5L')], note: null),
        Quote(id: 'Q2009', custId: 'C2010', leadId: null, status: 'accepted', amount: '₹2.03Cr', amountNum: 20300000, issued: '12 Jun 2026', valid: '26 Jun 2026', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '26 Jun 2026', owner: 'st', items: [QuoteItem(name: 'Showroom expansion — wing B', qty: 1, rate: '₹1.55Cr', amt: '₹1.55Cr'), QuoteItem(name: 'Facade & entrance', qty: 1, rate: '₹48L', amt: '₹48L')], note: 'Source quote for INV-3005.'),
        Quote(id: 'Q2012', custId: 'C2012', leadId: null, status: 'accepted', amount: '₹18L', amountNum: 1800000, issued: '25 Apr 2026', valid: '09 May 2026', template: 'Compact', payType: 'Lump sum', currency: 'INR', dueDate: '09 May 2026', owner: 'dr', items: [QuoteItem(name: 'Dining hall interiors', qty: 1, rate: '₹18L', amt: '₹18L')], note: 'Source quote for INV-3006.'),
        Quote(id: 'Q2053', custId: 'C2009', leadId: null, status: 'draft', amount: '₹64L', amountNum: 6400000, issued: '—', valid: '—', template: 'Standard', payType: 'Installments', currency: 'INR', dueDate: '—', owner: 'fa', items: [QuoteItem(name: 'Branch signage package', qty: 12, rate: '₹4L', amt: '₹48L'), QuoteItem(name: 'Reception refits', qty: 4, rate: '₹4L', amt: '₹16L')], note: 'Upsell draft — review with Arjun before sending.'),
        Quote(id: 'Q2054', custId: null, leadId: 'L1010', status: 'draft', amount: '₹18.5L', amountNum: 1850000, issued: '—', valid: '—', template: 'Compact', payType: 'Lump sum', currency: 'INR', dueDate: '—', owner: 'dr', items: [QuoteItem(name: 'Coworking floor refit', qty: 1, rate: '₹18.5L', amt: '₹18.5L')], note: null),
      ];
}
