import 'package:phosphor_flutter/phosphor_flutter.dart';
import '../../../../../app/theme/app_colors.dart';
import '../../../domain/entities/app_notification.dart';

/// Static notification seed — 1:1 port of the prototype's `notifs` array
/// (26 notifications across every module). Swap for a remote source at API
/// time; the UI is unchanged.
class NotificationsMockDataSource {
  const NotificationsMockDataSource();

  List<AppNotification> fetch() => [
        AppNotification(id: 'n1', category: 'leads', urgent: false, day: 'today', icon: PhosphorIconsFill.userPlus, iconColor: AppColors.blueBright, iconBg: AppColors.tintBlue, title: 'New lead assigned to you', body: 'Anjana Menon routed Malabar Gold Showroom into your pipeline.', time: '7m', unread: true, targetKind: 'lead', targetId: 'L1012'),
        AppNotification(id: 'n2', category: 'payments', urgent: false, day: 'today', icon: PhosphorIconsFill.currencyInr, iconColor: AppColors.success, iconBg: AppColors.tintGreen, title: 'Payment received — ₹46L', body: 'Aster Medcity OPD cleared the balance instalment via auto-debit.', time: '18m', unread: true, targetKind: 'payment', targetId: 'PAY-4006'),
        AppNotification(id: 'n3', category: 'tasks', urgent: true, day: 'today', icon: PhosphorIconsFill.clockClockwise, iconColor: AppColors.warning, iconBg: AppColors.tintAmber, title: 'Follow-up due today', body: 'Call Ramesh Pillai at 9:30 AM about the Kalyan Silks renewal.', time: '34m', unread: true, targetKind: 'followup', targetId: 'F901'),
        AppNotification(id: 'n4', category: 'system', urgent: true, day: 'today', icon: PhosphorIconsFill.plug, iconColor: AppColors.pending, iconBg: AppColors.tintPurple, title: 'Integration disconnected', body: 'WhatsApp Business token expired — outbound messages are paused.', time: '52m', unread: true, targetKind: 'none'),
        AppNotification(id: 'n5', category: 'payments', urgent: true, day: 'today', icon: PhosphorIconsFill.warningCircle, iconColor: AppColors.error, iconBg: AppColors.tintRed, title: 'Payment overdue — ₹18.3L', body: 'Marari Sands Resort on-handover instalment is past due.', time: '1h', unread: true, targetKind: 'payment', targetId: 'PAY-4004'),
        AppNotification(id: 'n6', category: 'tasks', urgent: true, day: 'today', icon: PhosphorIconsFill.warning, iconColor: AppColors.warningDeep, iconBg: AppColors.tintAmber, title: 'Task overdue', body: '“Trial room lighting install” at Kalyan Silks was due yesterday.', time: '3h', unread: true, targetKind: 'opstask', targetId: 'OT-104'),
        AppNotification(id: 'n7', category: 'leads', urgent: false, day: 'today', icon: PhosphorIconsFill.trendDown, iconColor: AppColors.blueBright, iconBg: AppColors.tintBlue, title: 'Hot lead going cold', body: 'No activity on Toms Auto Hyundai for 14 days — score dropped to 38.', time: '5h', unread: false, targetKind: 'lead', targetId: 'L1013'),
        AppNotification(id: 'n8', category: 'leads', urgent: false, day: 'yesterday', icon: PhosphorIconsFill.trophy, iconColor: AppColors.navy, iconBg: AppColors.tintNavy, title: 'Lead marked as Won', body: 'Aster Medcity OPD · ₹92L moved to Won by you.', time: '1d', unread: false, targetKind: 'lead', targetId: 'L1005'),
        AppNotification(id: 'n9', category: 'tasks', urgent: false, day: 'yesterday', icon: PhosphorIconsFill.listChecks, iconColor: AppColors.blueBright, iconBg: AppColors.tintBlue, title: 'Task assigned to you', body: '“Deck furniture BOQ” — Marari Sands Resort, due 12 Jul.', time: '1d', unread: true, targetKind: 'opstask', targetId: 'OT-110'),
        AppNotification(id: 'n10', category: 'payments', urgent: false, day: 'yesterday', icon: PhosphorIconsFill.receipt, iconColor: AppColors.blueBright, iconBg: AppColors.tintBlue, title: 'Invoice sent', body: 'INV-3004 issued to Federal Bank Aluva · ₹43L.', time: '1d', unread: false, targetKind: 'list', targetId: 'payments'),
        AppNotification(id: 'n11', category: 'system', urgent: false, day: 'yesterday', icon: PhosphorIconsFill.downloadSimple, iconColor: AppColors.textLabelAlt, iconBg: AppColors.tintGrey, title: 'Export ready', body: 'Your leads export (142 rows) is ready to download.', time: '1d', unread: false, targetKind: 'none'),
        AppNotification(id: 'n12', category: 'tasks', urgent: true, day: 'yesterday', icon: PhosphorIconsFill.timer, iconColor: AppColors.error, iconBg: AppColors.tintRed, title: 'SLA breached on a ticket', body: 'TKT-1005 — escalation: handover delay concern.', time: '1d', unread: true, targetKind: 'ticket', targetId: 'TKT-1005'),
        AppNotification(id: 'n13', category: 'leads', urgent: false, day: 'earlier', icon: PhosphorIconsFill.fileText, iconColor: AppColors.success, iconBg: AppColors.tintGreen, title: 'Quote accepted', body: 'Kalyan Silks accepted #Q2051 · ₹38L boutique wing fit-out.', time: '2d', unread: false, targetKind: 'quote', targetId: 'Q2051'),
        AppNotification(id: 'n14', category: 'payments', urgent: false, day: 'earlier', icon: PhosphorIconsFill.warningCircle, iconColor: AppColors.error, iconBg: AppColors.tintRed, title: 'Payment overdue — ₹43L', body: 'Federal Bank Aluva on-handover instalment is past due.', time: '3d', unread: false, targetKind: 'payment', targetId: 'PAY-4009'),
        AppNotification(id: 'n15', category: 'tasks', urgent: false, day: 'earlier', icon: PhosphorIconsFill.envelopeSimple, iconColor: AppColors.warning, iconBg: AppColors.tintAmber, title: 'Follow-up overdue', body: 'Email Suresh Nair at KIMS Clinic — was due 21 Jun.', time: '4d', unread: false, targetKind: 'followup', targetId: 'F906'),
        AppNotification(id: 'n16', category: 'system', urgent: false, day: 'earlier', icon: PhosphorIconsFill.userCirclePlus, iconColor: AppColors.textLabelAlt, iconBg: AppColors.tintGrey, title: 'New member added', body: 'Fariz Ahmed joined Team South as a Project associate.', time: '5d', unread: false, targetKind: 'none'),
        AppNotification(id: 'n17', category: 'ops', urgent: true, day: 'today', icon: PhosphorIconsFill.kanban, iconColor: AppColors.error, iconBg: AppColors.tintRed, title: 'Project slipping', body: 'Kalyan Silks showroom fit-out is 3 tasks behind its handover date.', time: '22m', unread: true, targetKind: 'project', targetId: 'PRJ-2401'),
        AppNotification(id: 'n18', category: 'ops', urgent: false, day: 'today', icon: PhosphorIconsFill.checkCircle, iconColor: AppColors.success, iconBg: AppColors.tintGreen, title: 'Task moved to review', body: 'Rahul Krishnan sent “VM units fabrication” for your review.', time: '2h', unread: true, targetKind: 'opstask', targetId: 'OT-105'),
        AppNotification(id: 'n19', category: 'help', urgent: true, day: 'today', icon: PhosphorIconsFill.ticket, iconColor: AppColors.error, iconBg: AppColors.tintRed, title: 'Urgent ticket assigned', body: 'TKT-1015 — loose wiring at the Kalyan Silks cash counter.', time: '41m', unread: true, targetKind: 'ticket', targetId: 'TKT-1015'),
        AppNotification(id: 'n20', category: 'help', urgent: false, day: 'today', icon: PhosphorIconsFill.chatCircleDots, iconColor: AppColors.blueBright, iconBg: AppColors.tintBlue, title: 'Customer replied', body: 'Aboobacker Haji responded on TKT-1005 — handover delay concern.', time: '4h', unread: false, targetKind: 'ticket', targetId: 'TKT-1005'),
        AppNotification(id: 'n21', category: 'ops', urgent: false, day: 'yesterday', icon: PhosphorIconsFill.flag, iconColor: AppColors.pending, iconBg: AppColors.tintPurple, title: 'Milestone approved', body: '“Façade signage approval” cleared at Kalyan Silks showroom.', time: '1d', unread: false, targetKind: 'opstask', targetId: 'OT-103'),
        AppNotification(id: 'n22', category: 'training', urgent: false, day: 'yesterday', icon: PhosphorIconsFill.graduationCap, iconColor: AppColors.blueBright, iconBg: AppColors.tintBlue, title: 'Course assigned to you', body: '“CRM Fundamentals” is mandatory — due 20 Aug.', time: '1d', unread: true, targetKind: 'list', targetId: 'lmsMy'),
        AppNotification(id: 'n23', category: 'help', urgent: false, day: 'yesterday', icon: PhosphorIconsFill.pauseCircle, iconColor: AppColors.warning, iconBg: AppColors.tintAmber, title: 'Ticket waiting on customer', body: 'TKT-1010 paused — revised BOQ pending from Marari Sands.', time: '1d', unread: false, targetKind: 'ticket', targetId: 'TKT-1010'),
        AppNotification(id: 'n24', category: 'training', urgent: false, day: 'earlier', icon: PhosphorIconsFill.medal, iconColor: AppColors.success, iconBg: AppColors.tintGreen, title: 'Course completed', body: 'You finished “Site Safety Basics” — 40 points added.', time: '3d', unread: false, targetKind: 'list', targetId: 'rewards'),
        AppNotification(id: 'n25', category: 'ops', urgent: false, day: 'earlier', icon: PhosphorIconsFill.briefcase, iconColor: AppColors.blueBright, iconBg: AppColors.tintBlue, title: 'Added to a project', body: 'Anjana Menon added you to Marari Sands villa interiors.', time: '4d', unread: false, targetKind: 'project', targetId: 'PRJ-2403'),
        AppNotification(id: 'n26', category: 'system', urgent: false, day: 'earlier', icon: PhosphorIconsFill.creditCard, iconColor: AppColors.textLabelAlt, iconBg: AppColors.tintGrey, title: 'Plan renews in 7 days', body: 'Clozr Growth · 12 seats · auto-renews on 03 Aug.', time: '6d', unread: false, targetKind: 'list', targetId: 'billing'),
      ];
}
