import '../../../domain/entities/ticket.dart';

/// Static ticket seed — a 1:1 port of the prototype's `TKTSEED` array. This is
/// the ONLY place ticket sample data lives. To integrate the API, replace this
/// class with a remote data source returning `List<Ticket>`; nothing else
/// changes. The customer / project reference maps and the SLA target matrix
/// (`TKTSLA`) are ported here too so helpdesk has no cross-feature dependency.
class TicketsMockDataSource {
  const TicketsMockDataSource();

  List<Ticket> fetchTickets() => const [
        Ticket(id: 'TKT-1024', subject: 'Confirm veneer shade before rework', cat: 'Query', custId: 'C2003', contact: 'Jose Kuriakose', channel: 'Email', status: 'pending', pri: 'Medium', assignees: ['me'], product: 'Design Services', projId: null, taskId: null, created: '07 Jul, 2:10 PM', responded: '07 Jul, 3:00 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-14T18:00:00', resolveByLabel: '14 Jul, 6:00 PM', desc: 'Awaiting the customer’s confirmation on the veneer shade before scheduling the rework crew.'),
        Ticket(id: 'TKT-1013', subject: 'Water seepage near display window', cat: 'Complaint', custId: 'C2002', contact: 'Aboobacker Haji', channel: 'Phone', status: 'open', pri: 'High', assignees: ['dr'], product: 'Fit-out', projId: null, taskId: null, created: '08 Jul, 5:10 PM', responded: '08 Jul, 6:00 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-09T14:00:00', resolveByLabel: '09 Jul, 2:00 PM', desc: 'Seepage patch spreading near the display window base. Needs sealing before the weekend.'),
        Ticket(id: 'TKT-1014', subject: 'Replace cracked mirror panel', cat: 'Request', custId: 'C2005', contact: 'Priya Varma', channel: 'WhatsApp', status: 'open', pri: 'Medium', assignees: ['am'], product: 'Fit-out', projId: null, taskId: null, created: '08 Jul, 12:30 PM', responded: '08 Jul, 1:15 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-09T16:30:00', resolveByLabel: '09 Jul, 4:30 PM', desc: 'Full-height mirror panel near the trial rooms has a hairline crack. Replacement requested.'),
        Ticket(id: 'TKT-1015', subject: 'Loose wiring at cash counter', cat: 'Complaint', custId: 'C2001', contact: 'Ramesh Pillai', channel: 'Phone', status: 'new', pri: 'Urgent', assignees: ['me'], product: 'MEP & Services', projId: null, taskId: null, created: '09 Jul, 9:00 AM', responded: null, resolved: null, respByISO: '2026-07-09T13:00:00', respByLabel: '1:00 PM', resolveByISO: '2026-07-10T18:00:00', resolveByLabel: '10 Jul, 6:00 PM', desc: 'Exposed wiring under the cash counter — safety concern flagged by store staff.'),
        Ticket(id: 'TKT-1016', subject: 'AMC quarterly service visit', cat: 'Request', custId: 'C2003', contact: 'Jose Kuriakose', channel: 'Email', status: 'open', pri: 'Low', assignees: ['an'], product: 'AMC / Maintenance', projId: null, taskId: null, created: '07 Jul, 10:00 AM', responded: '07 Jul, 11:20 AM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-10T18:00:00', resolveByLabel: '10 Jul, 6:00 PM', desc: 'Scheduled quarterly AMC visit — HVAC filters and joinery hinges.'),
        Ticket(id: 'TKT-1017', subject: 'Carpet stain — banquet foyer', cat: 'Complaint', custId: 'C2004', contact: 'Nikhil Menon', channel: 'Walk-in', status: 'open', pri: 'Low', assignees: ['rk'], product: 'Fit-out', projId: null, taskId: null, created: '08 Jul, 9:45 AM', responded: '08 Jul, 10:30 AM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-11T12:00:00', resolveByLabel: '11 Jul, 12:00 PM', desc: 'Deep stain on the foyer carpet after an event. Professional cleaning needed.'),
        Ticket(id: 'TKT-1018', subject: 'Extra keys for storage units', cat: 'Request', custId: 'C2001', contact: 'Ramesh Pillai', channel: 'WhatsApp', status: 'open', pri: 'Low', assignees: ['dr'], product: 'Joinery', projId: null, taskId: null, created: '07 Jul, 4:00 PM', responded: '07 Jul, 5:10 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-12T18:00:00', resolveByLabel: '12 Jul, 6:00 PM', desc: 'Two spare key sets requested for the back-store storage units.'),
        Ticket(id: 'TKT-1019', subject: 'Signage vinyl peeling at entrance', cat: 'Complaint', custId: 'C2006', contact: 'Nikhil Menon', channel: 'Email', status: 'new', pri: 'Medium', assignees: ['me'], product: 'MEP & Services', projId: null, taskId: null, created: '09 Jul, 7:50 AM', responded: null, resolved: null, respByISO: '2026-07-10T09:00:00', respByLabel: '10 Jul, 9:00 AM', resolveByISO: '2026-07-14T18:00:00', resolveByLabel: '14 Jul, 6:00 PM', desc: 'Entrance signage vinyl lettering peeling at the corners.'),
        Ticket(id: 'TKT-1020', subject: 'Dimmer switch replacement', cat: 'Request', custId: 'C2005', contact: 'Priya Varma', channel: 'Phone', status: 'open', pri: 'Medium', assignees: ['am'], product: 'MEP & Services', projId: null, taskId: null, created: '06 Jul, 2:20 PM', responded: '06 Jul, 3:00 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-13T17:00:00', resolveByLabel: '13 Jul, 5:00 PM', desc: 'Lounge dimmer module faulty — flickers at low levels. Replace with same series.'),
        Ticket(id: 'TKT-1021', subject: 'Warranty doc for lounge seating', cat: 'Query', custId: 'C2004', contact: 'Nikhil Menon', channel: 'Email', status: 'open', pri: 'Low', assignees: ['an'], product: 'Furniture', projId: null, taskId: null, created: '05 Jul, 3:30 PM', responded: '05 Jul, 4:45 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-16T18:00:00', resolveByLabel: '16 Jul, 6:00 PM', desc: 'Customer wants the upholstery warranty certificate for the lounge seating.'),
        Ticket(id: 'TKT-1022', subject: 'Pest control before handover', cat: 'Request', custId: 'C2002', contact: 'Aboobacker Haji', channel: 'Phone', status: 'open', pri: 'Medium', assignees: ['fa'], product: null, projId: null, taskId: null, created: '06 Jul, 11:00 AM', responded: '06 Jul, 12:10 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-17T10:00:00', resolveByLabel: '17 Jul, 10:00 AM', desc: 'Anti-termite and general pest treatment requested before the handover walkthrough.'),
        Ticket(id: 'TKT-1023', subject: 'Touch-up paint — corridor scuffs', cat: 'Complaint', custId: 'C2003', contact: 'Jose Kuriakose', channel: 'Walk-in', status: 'open', pri: 'Low', assignees: ['dr'], product: 'Fit-out', projId: null, taskId: null, created: '05 Jul, 9:30 AM', responded: '05 Jul, 10:00 AM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-18T18:00:00', resolveByLabel: '18 Jul, 6:00 PM', desc: 'Scuff marks along the service corridor walls — schedule a touch-up crew.'),
        Ticket(id: 'TKT-1012', subject: 'AC unit not cooling in trial room', cat: 'Complaint', custId: 'C2001', contact: 'Ramesh Pillai', channel: 'Phone', status: 'open', pri: 'Urgent', assignees: ['rk'], product: 'AMC / Maintenance', projId: 'PRJ-2401', taskId: 'OT-104', created: '08 Jul, 9:12 AM', responded: '08 Jul, 1:12 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-20T17:00:00', resolveByLabel: '20 Jul, 5:00 PM', desc: 'Trial room AC stops cooling after 20 minutes. Customer reports recurring since last week.'),
        Ticket(id: 'TKT-1011', subject: 'Signage light flickering', cat: 'Complaint', custId: 'C2002', contact: 'Aboobacker Haji', channel: 'WhatsApp', status: 'new', pri: 'High', assignees: ['me'], product: 'MEP & Services', projId: null, taskId: null, created: '09 Jul, 8:40 AM', responded: null, resolved: null, respByISO: '2026-07-09T12:40:00', respByLabel: '12:40 PM', resolveByISO: '2026-07-11T18:00:00', resolveByLabel: '11 Jul, 6:00 PM', desc: 'Façade signage flickers intermittently at night. Needs electrician visit.'),
        Ticket(id: 'TKT-1010', subject: 'Request revised BOQ for deck furniture', cat: 'Request', custId: 'C2003', contact: 'Jose Kuriakose', channel: 'Email', status: 'pending', pri: 'Medium', assignees: ['an'], product: 'Design Services', projId: 'PRJ-2403', taskId: 'OT-110', created: '05 Jul, 11:00 AM', responded: '05 Jul, 12:30 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-12T15:00:00', resolveByLabel: '12 Jul, 3:00 PM', desc: 'Customer asked for a revised BOQ with an alternate teak grade. Awaiting their material confirmation.'),
        Ticket(id: 'TKT-1009', subject: 'Snag: chipped laminate on counter', cat: 'Complaint', custId: 'C2001', contact: 'Ramesh Pillai', channel: 'Walk-in', status: 'open', pri: 'Medium', assignees: ['rk', 'dr'], product: 'Joinery', projId: 'PRJ-2401', taskId: 'OT-102', created: '07 Jul, 3:20 PM', responded: '07 Jul, 4:05 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-09T03:30:00', resolveByLabel: '09 Jul, 3:30 AM', desc: 'Cash counter laminate chipped at the edge — needs rework before handover.'),
        Ticket(id: 'TKT-1008', subject: 'Billing query on last invoice', cat: 'Query', custId: 'C2006', contact: 'Nikhil Menon', channel: 'Email', status: 'open', pri: 'Low', assignees: ['me'], product: null, projId: null, taskId: null, created: '06 Jul, 10:15 AM', responded: '06 Jul, 5:40 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-09T05:15:00', resolveByLabel: '09 Jul, 5:15 AM', desc: 'Customer questions GST split on INV-3008. Finance to clarify.'),
        Ticket(id: 'TKT-1007', subject: 'Add power points in lounge', cat: 'Request', custId: 'C2005', contact: 'Priya Varma', channel: 'Phone', status: 'resolved', pri: 'Medium', assignees: ['me'], product: 'MEP & Services', projId: null, taskId: null, created: '28 Jun, 9:00 AM', responded: '28 Jun, 10:12 AM', resolved: '09 Jul, 9:05 AM', respByISO: null, respByLabel: null, resolveByISO: '2026-07-03T18:00:00', resolveByLabel: '03 Jul, 6:00 PM', desc: 'Customer requested four extra power points in the waiting lounge. Completed and verified.'),
        Ticket(id: 'TKT-1006', subject: 'Door handle loose — banquet entry', cat: 'Complaint', custId: 'C2004', contact: 'Nikhil Menon', channel: 'WhatsApp', status: 'closed', pri: 'Low', assignees: ['rk'], product: 'Joinery', projId: 'PRJ-2405', taskId: null, created: '20 Jun, 2:00 PM', responded: '20 Jun, 2:40 PM', resolved: '22 Jun, 11:00 AM', respByISO: null, respByLabel: null, resolveByISO: '2026-06-23T18:00:00', resolveByLabel: '23 Jun, 6:00 PM', desc: 'Loose handle on the main banquet entry door. Tightened and checked.'),
        Ticket(id: 'TKT-1005', subject: 'Escalation: handover delay concern', cat: 'Complaint', custId: 'C2002', contact: 'Aboobacker Haji', channel: 'Phone', status: 'open', pri: 'Urgent', assignees: ['me', 'rk'], product: null, projId: 'PRJ-2402', taskId: 'OT-105', created: '06 Jul, 4:00 PM', responded: '06 Jul, 6:30 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-09T00:30:00', resolveByLabel: '09 Jul, 12:30 AM', desc: 'Customer escalated over the flagship handover timeline. Needs a revised schedule call.'),
        Ticket(id: 'TKT-1004', subject: 'Clarify AMC coverage scope', cat: 'Query', custId: 'C2003', contact: 'Jose Kuriakose', channel: 'Email', status: 'new', pri: 'Low', assignees: ['an'], product: 'AMC / Maintenance', projId: null, taskId: null, created: '09 Jul, 7:30 AM', responded: null, resolved: null, respByISO: '2026-07-09T11:30:00', respByLabel: '11:30 AM', resolveByISO: '2026-07-13T18:00:00', resolveByLabel: '13 Jul, 6:00 PM', desc: 'What does the annual maintenance contract cover for civil vs. MEP items?'),
        Ticket(id: 'TKT-1003', subject: 'Paint touch-up in reception', cat: 'Complaint', custId: 'C2005', contact: 'Priya Varma', channel: 'Walk-in', status: 'resolved', pri: 'Low', assignees: ['me'], product: 'Fit-out', projId: null, taskId: null, created: '25 Jun, 11:00 AM', responded: '25 Jun, 11:50 AM', resolved: '09 Jul, 8:20 AM', respByISO: null, respByLabel: null, resolveByISO: '2026-06-28T18:00:00', resolveByLabel: '28 Jun, 6:00 PM', desc: 'Minor scuff marks near the reception desk. Repainted.'),
        Ticket(id: 'TKT-1002', subject: 'Wrong fabric on lounge seating', cat: 'Complaint', custId: 'C2004', contact: 'Nikhil Menon', channel: 'Email', status: 'open', pri: 'High', assignees: ['rk'], product: 'Furniture', projId: 'PRJ-2405', taskId: null, created: '04 Jul, 9:20 AM', responded: '04 Jul, 12:00 PM', resolved: null, respByISO: null, respByLabel: null, resolveByISO: '2026-07-15T18:00:00', resolveByLabel: '15 Jul, 6:00 PM', desc: 'Lounge chairs delivered in the wrong fabric shade. Replacement to be arranged.'),
        Ticket(id: 'TKT-1001', subject: 'Handover documentation request', cat: 'Request', custId: 'C2001', contact: 'Ramesh Pillai', channel: 'Email', status: 'closed', pri: 'Medium', assignees: ['me'], product: null, projId: 'PRJ-2401', taskId: null, created: '15 Jun, 10:00 AM', responded: '15 Jun, 11:00 AM', resolved: '18 Jun, 4:32 PM', respByISO: null, respByLabel: null, resolveByISO: '2026-06-20T18:00:00', resolveByLabel: '20 Jun, 6:00 PM', desc: 'Customer requested the full handover document set — drawings, warranties and O&M manuals.'),
      ];
}

/// Customer + project reference lookups and the SLA target matrix, ported from
/// the prototype so ticket screens can resolve `custId` / `projId` without a
/// cross-feature dependency.
class TicketDirectory {
  TicketDirectory._();

  static const Map<String, TicketCustomer> customers = {
    'C2001': TicketCustomer('C2001', 'Ramesh Pillai', 'Kalyan Silks'),
    'C2002': TicketCustomer('C2002', 'Aboobacker Haji', 'Lulu Fashion Store'),
    'C2003': TicketCustomer('C2003', 'Jose Kuriakose', 'Marari Sands Resort'),
    'C2004': TicketCustomer('C2004', 'Nikhil Menon', 'Taj Gateway Annexe'),
    'C2005': TicketCustomer('C2005', 'Priya Varma', 'Aster Medcity OPD'),
    'C2006': TicketCustomer('C2006', 'Suresh Nair', 'KIMS Clinic'),
    'C2007': TicketCustomer('C2007', 'Biju Thomas', 'Federal Bank Aluva'),
    'C2008': TicketCustomer('C2008', 'Anand Krishnan', 'Infopark Tower B'),
    'C2009': TicketCustomer('C2009', 'Geetha Mohan', 'Technopark Tejaswini'),
  };

  static const Map<String, TicketProject> projects = {
    'PRJ-2401': TicketProject('PRJ-2401', 'Kalyan Silks showroom fit-out', '₹18L'),
    'PRJ-2402': TicketProject('PRJ-2402', 'Lulu flagship store interiors', '₹36.5L'),
    'PRJ-2403': TicketProject('PRJ-2403', 'Marari Sands villa refresh', '₹22L'),
    'PRJ-2405': TicketProject('PRJ-2405', 'Taj Gateway banquet hall', '₹27L'),
  };

  /// `TKTSLA` — the default SLA target matrix keyed by priority.
  static const Map<String, SlaTarget> sla = {
    'Urgent': SlaTarget(respLabel: '1h', resLabel: '8h', respISO: '2026-07-09T10:00:00', resISO: '2026-07-09T17:00:00', lineResp: '1h', lineRes: '8h'),
    'High': SlaTarget(respLabel: '2h', resLabel: '1 day', respISO: '2026-07-09T11:00:00', resISO: '2026-07-10T09:00:00', lineResp: '2h', lineRes: '1 day'),
    'Medium': SlaTarget(respLabel: '4h', resLabel: '3 days', respISO: '2026-07-09T13:00:00', resISO: '2026-07-12T09:00:00', lineResp: '4h', lineRes: '3 days'),
    'Low': SlaTarget(respLabel: '8h', resLabel: '5 days', respISO: '2026-07-09T17:00:00', resISO: '2026-07-14T09:00:00', lineResp: '8h', lineRes: '5 days'),
  };

  static TicketCustomer? customer(String? id) => id == null ? null : customers[id];
  static TicketProject? project(String? id) => id == null ? null : projects[id];
}
