import 'package:phosphor_flutter/phosphor_flutter.dart';
import '../../../../../app/router/routes.dart';
import '../../../domain/entities/dash_colors.dart';
import '../../../domain/entities/dashboard_models.dart';

/// Seeded dashboard figures, ported 1:1 from the prototype's dashboard
/// view-models (`adminKpis`, `dmKpis`, `moKpis`, `mhKpis`, funnels, donuts,
/// rosters, …). Aggregates are computed against the prototype seed at the
/// reference clock (09 Jul 2026, 09:41) with the "All teams" scope.
class DashboardMockDataSource {
  const DashboardMockDataSource();

  DashboardData load() => const DashboardData(
        // ─────────────────────────── Business / admin ───────────────────────
        adminKpis: [
          DashKpi(
            icon: PhosphorIconsFill.trendUp,
            accent: DashColors.green,
            iconBg: DashColors.tintGreen,
            value: '₹18.4',
            unit: 'L',
            label: 'Sales pipeline',
            sub: 'Pipeline value, all stages',
            trendPositive: true,
            trend: '12.3%',
            arrow: DashTrendArrow.up,
            spark: [12, 13, 12.5, 14, 15, 16, 18.4],
            route: Routes.leads,
          ),
          DashKpi(
            icon: PhosphorIconsFill.wallet,
            accent: DashColors.blue,
            iconBg: DashColors.tintBlue,
            value: '₹9.4',
            unit: 'L',
            label: 'Payments collected',
            sub: 'Of ₹22.2L expected',
            trendPositive: true,
            trend: '12.3%',
            arrow: DashTrendArrow.up,
            spark: [4, 5, 5.5, 6.5, 7, 8.4, 9.4],
            route: Routes.payments,
          ),
          DashKpi(
            icon: PhosphorIconsFill.warningCircle,
            accent: DashColors.red,
            iconBg: DashColors.tintRed,
            value: '₹4.4',
            unit: 'L',
            label: 'Overdue receivables',
            sub: 'Across 23 customers',
            trendPositive: false,
            trend: '14%',
            arrow: DashTrendArrow.down,
            spark: [2.5, 3, 2.8, 3.4, 3.8, 4.1, 4.4],
            route: Routes.payments,
          ),
          DashKpi(
            icon: PhosphorIconsFill.ticket,
            accent: DashColors.amber,
            iconBg: DashColors.tintAmber,
            value: '147',
            unit: '',
            label: 'Open tickets',
            sub: 'Across all priorities',
            trendPositive: true,
            trend: '8%',
            arrow: DashTrendArrow.down,
            spark: [180, 175, 168, 160, 155, 150, 147],
            route: Routes.tickets,
          ),
        ],
        receivablesTotal: '₹1.05 cr',
        receivablesSub: '₹54.40L overdue · ₹50.60L upcoming',
        overdueTotal: 'Overdue · ₹54.40L',
        upcomingTotal: 'Upcoming · ₹50.60L',
        aging: [
          DashAgingRow('0–30 days', '₹18.2L', DashColors.grey, 34),
          DashAgingRow('31–60 days', '₹12.4L', DashColors.teal, 23),
          DashAgingRow('61–90 days', '₹13.6L', DashColors.navyMid, 25),
          DashAgingRow('90+ days', '₹10.2L', DashColors.red, 18),
        ],
        upcoming: [
          DashLabelAmt('Due today', '₹6.4L'),
          DashLabelAmt('Due in 7 days', '₹12.1L'),
          DashLabelAmt('Due in 30 days', '₹18.5L'),
          DashLabelAmt('Due in 90 days', '₹13.6L'),
        ],
        outstanding: [
          DashOutstanding('Kalyan Silks', 112, '₹12.2L', DashColors.red, 100),
          DashOutstanding('Bismi Hypermarket', 91, '₹9.2L', DashColors.navyMid, 78),
          DashOutstanding('Meridian Group', 48, '₹9.2L', DashColors.teal, 55),
          DashOutstanding('Sunrise Hotels', 43, '₹9.2L', DashColors.teal, 48),
          DashOutstanding('Orbit Health', 22, '₹9.2L', DashColors.grey, 30),
        ],
        outstandingTotal: '₹50.60 L',
        topCustomers: [
          DashTopCustomer('Nirapara Supermarket', '2 orders · 2d ago', '₹2.21Cr'),
          DashTopCustomer('Toms Auto Hyundai', '3 orders · 2d ago', '₹2.21Cr'),
          DashTopCustomer('Malabar Gold Showroom', '4 orders · 2d ago', '₹2.03Cr'),
          DashTopCustomer('Bismi Hypermarket', '5 orders · 2d ago', '₹2.03Cr'),
        ],

        // ─────────────────────────────── CRM ────────────────────────────────
        crmKpis: [
          DashKpi(
            icon: PhosphorIconsFill.userPlus,
            accent: DashColors.green,
            iconBg: DashColors.tintGreen,
            value: '142',
            unit: '',
            label: 'New leads',
            sub: 'This week, all sources',
            trendPositive: true,
            trend: '18.3%',
            arrow: DashTrendArrow.up,
            spark: [96, 104, 100, 112, 120, 131, 142],
            route: Routes.leads,
          ),
          DashKpi(
            icon: PhosphorIconsFill.target,
            accent: DashColors.green,
            iconBg: DashColors.tintGreen,
            value: '23',
            unit: '%',
            label: 'Win rate',
            sub: 'Won / qualified ratio',
            trendPositive: true,
            trend: '4.3%',
            arrow: DashTrendArrow.up,
            spark: [19, 20, 20, 21, 22, 22, 23],
            route: Routes.leads,
          ),
          DashKpi(
            icon: PhosphorIconsFill.clockCountdown,
            accent: DashColors.red,
            iconBg: DashColors.tintRed,
            value: '14',
            unit: 'minutes',
            label: 'First to response',
            sub: 'Initial engagement time',
            trendPositive: false,
            trend: '3 min',
            arrow: DashTrendArrow.up,
            spark: [9, 10, 11, 11, 12, 13, 14],
            route: Routes.followups,
          ),
          DashKpi(
            icon: PhosphorIconsFill.fileText,
            accent: DashColors.blue,
            iconBg: DashColors.tintBlue,
            value: '52',
            unit: '%',
            label: 'Quote acceptance',
            sub: 'Conversion rate',
            trendPositive: true,
            trend: '5%',
            arrow: DashTrendArrow.up,
            progress: 0.52,
            route: Routes.quotes,
          ),
        ],
        crmFunnel: [
          DashBar('New', 142),
          DashBar('Active', 86),
          DashBar('Negotiation', 31),
          DashBar('Won', 22),
          DashBar('Lost', 18),
        ],
        crmInflow: DashTrend(
          seriesA: [18, 21, 24, 22, 25, 29, 33, 31, 36, 38, 41, 44], // created
          seriesB: [7, 9, 11, 10, 12, 14, 16, 15, 18, 19, 21, 23], // won
          min: 0,
          max: 50,
          axisLabels: ['Jan', 'Apr', 'Aug', 'Dec'],
        ),
        crmAttention: [
          DashAttentionCard(
            value: '12',
            label: 'Payments missed',
            delta: '+3',
            arrow: DashTrendArrow.up,
            positive: false,
            neutral: false,
            note: 'Worsening',
            noteColor: DashColors.red,
            route: Routes.payments,
          ),
          DashAttentionCard(
            value: '28',
            label: 'Followups missed',
            delta: '0',
            arrow: DashTrendArrow.flat,
            positive: false,
            neutral: true,
            note: 'Steady',
            noteColor: DashColors.textMid,
            route: Routes.followups,
          ),
          DashAttentionCard(
            value: '19',
            label: 'Tasks missed',
            delta: '-5',
            arrow: DashTrendArrow.down,
            positive: true,
            neutral: false,
            note: 'Improving',
            noteColor: DashColors.green,
            route: Routes.tasks,
          ),
          DashAttentionCard(
            value: '14',
            label: 'Lost after quote',
            delta: '+3',
            arrow: DashTrendArrow.up,
            positive: false,
            neutral: false,
            note: 'Worsening',
            noteColor: DashColors.red,
            route: Routes.leads,
          ),
        ],
        crmSources: [
          DashSource(name: 'Website', leads: 10, won: 2, pct: '12%', cycle: '18d', closed: '₹12.4L', up: true),
          DashSource(name: 'Referrals', leads: 48, won: 12, pct: '11%', cycle: '22d', closed: '₹48.6L', up: null),
          DashSource(name: 'LinkedIn', leads: 23, won: 5, pct: '25%', cycle: '26d', closed: '₹21.2L', up: null),
          DashSource(name: 'Google Ads', leads: 32, won: 12, pct: '22%', cycle: '19d', closed: '₹34.8L', up: null),
          DashSource(name: 'Cold call', leads: 12, won: 2, pct: '36%', cycle: '31d', closed: '₹8.4L', up: false),
        ],
        crmStuck: {
          'stale': [
            DashStuckRow('Toms Auto Hyundai', 'Vinod Kumar · no activity', '₹95L', '14 days ago'),
            DashStuckRow('Workafella Coworking', 'Sangeeth Raj · no activity', '₹42L', '11 days ago'),
            DashStuckRow('Nirapara Supermarket', 'Mathew George · no activity', '₹27L', '9 days ago'),
            DashStuckRow('Malabar Gold Showroom', 'Ashraf Ali · awaiting reply', '₹2.03Cr', '8 days ago'),
          ],
          'quotes': [
            DashStuckRow('Lulu Fashion Store', '#Q2002 · Rahul Krishnan', '₹58.9L', '72 days ago'),
            DashStuckRow('Taj Gateway Annexe', '#Q2004 · Deepak Raj', '₹85.7L', '48 days ago'),
            DashStuckRow('Kalyan Silks', '#Q2050 · Anjana Menon', '₹2.5L', '37 days ago'),
          ],
          'payments': [
            DashStuckRow('Marari Sands Resort', 'On handover (30%) · Fariz Ahmed', '₹18.3L', '15 days ago'),
            DashStuckRow('Federal Bank Aluva', 'On handover (30%) · Anjana Menon', '₹43L', '15 days ago'),
          ],
          'wonnc': [
            DashStuckRow('Federal Bank Aluva', 'Won lead · no project created', '₹1.29Cr', '40 days ago'),
            DashStuckRow('Malabar Gold Showroom', 'Active customer · no project', '₹2.03Cr', '62 days ago'),
          ],
        },
        crmEmployees: [
          DashCrmEmployee('st', 10, 2, '₹12.4L', '22 min', '2 m ago'),
          DashCrmEmployee('rk', 48, 12, '₹48.6L', '31 min', '1 h ago'),
          DashCrmEmployee('am', 23, 5, '₹21.2L', '18 min', '7 m ago'),
          DashCrmEmployee('dr', 32, 12, '₹34.8L', '15 min', '22 m ago'),
        ],

        // ─────────────────────────── Operations ─────────────────────────────
        opsKpis: [
          DashKpi(
            icon: PhosphorIconsFill.briefcase,
            accent: DashColors.green,
            iconBg: DashColors.tintGreen,
            value: '3',
            unit: '',
            label: 'Active Projects',
            sub: 'In delivery right now',
            trendPositive: true,
            trend: '2.3%',
            arrow: DashTrendArrow.up,
            spark: [2, 2, 3, 3, 3, 3, 3],
            route: Routes.opsProjects,
          ),
          DashKpi(
            icon: PhosphorIconsFill.flag,
            accent: DashColors.red,
            iconBg: DashColors.tintRed,
            value: '1 / 9',
            unit: '',
            label: 'Projects Overdue',
            sub: 'Past their end date',
            trendPositive: false,
            trend: '2',
            arrow: DashTrendArrow.down,
            progress: 0.11,
            route: Routes.opsProjects,
          ),
          DashKpi(
            icon: PhosphorIconsFill.listChecks,
            accent: DashColors.red,
            iconBg: DashColors.tintRed,
            value: '2',
            unit: '',
            label: 'Tasks Overdue',
            sub: 'Across all projects',
            trendPositive: false,
            trend: '8.4%',
            arrow: DashTrendArrow.down,
            spark: [5, 5, 4, 4, 3, 3, 2],
            route: Routes.opsTasks,
          ),
          DashKpi(
            icon: PhosphorIconsFill.clock,
            accent: DashColors.red,
            iconBg: DashColors.tintRed,
            value: '48',
            unit: 'days',
            label: 'Avg Project Cycle',
            sub: 'Start to handover',
            trendPositive: false,
            trend: '2.4%',
            arrow: DashTrendArrow.up,
            spark: [43, 44, 44, 45, 46, 47, 48],
            route: Routes.opsProjects,
          ),
        ],
        opsStatus: [
          DashDonutPart('Complete', DashColors.purple, 2),
          DashDonutPart('On track', DashColors.green, 2),
          DashDonutPart('Planning', DashColors.grey, 2),
          DashDonutPart('On hold', DashColors.amber, 2),
          DashDonutPart('Overdue', DashColors.red, 1),
        ],
        opsOverdue: [
          DashOverdueTask('VM units fabrication', 'Lulu flagship store interiors · Rahul',
              '₹36.5L', '9d overdue', Routes.opsTaskDetail),
          DashOverdueTask('Joinery shop drawings', 'Kalyan Silks showroom fit-out · Manoj, Sneha',
              '₹18L', '4d overdue', Routes.opsTaskDetail),
        ],
        opsProjects: [
          // status category ('active' | 'onhold') drives segment filtering.
          DashProjectRow('Taj Gateway banquet hall', 'Rahul Krishnan', '₹27L', 'Overdue',
              DashColors.red, 55, -11, 'active'),
          DashProjectRow('Kalyan Silks showroom fit-out', 'Anjana Menon', '₹18L', 'Active',
              DashColors.green, 62, 52, 'active'),
          DashProjectRow('Lulu flagship store interiors', 'Manoj Varma', '₹36.5L', 'Active',
              DashColors.green, 41, 73, 'active'),
          DashProjectRow('Forum Mall kiosks rollout', 'Rahul Krishnan', '₹9L', 'On hold',
              DashColors.amber, 20, 21, 'onhold'),
          DashProjectRow('Grand Hyatt spa joinery', 'Anjana Menon', '₹19L', 'On hold',
              DashColors.amber, 34, 37, 'onhold'),
        ],
        opsRoster: [
          DashRosterRow('me', '3 projects · 4 open tasks', '1 overdue', true),
          DashRosterRow('an', '0 projects · 2 open tasks', '0 overdue', false),
          DashRosterRow('am', '1 project · 1 open task', '0 overdue', false),
          DashRosterRow('rk', '3 projects · 2 open tasks', '1 overdue', true),
          DashRosterRow('st', '1 project · 1 open task', '1 overdue', true),
          DashRosterRow('dr', '0 projects · 1 open task', '0 overdue', false),
        ],

        // ──────────────────────────── Helpdesk ──────────────────────────────
        helpKpis: [
          DashKpi(
            icon: PhosphorIconsFill.ticket,
            accent: DashColors.blue,
            iconBg: DashColors.tintBlue,
            value: '20',
            unit: '',
            label: 'Open Tickets',
            sub: 'New, open & pending',
            trendPositive: true,
            trend: '8%',
            arrow: DashTrendArrow.down,
            spark: [11, 11, 10, 10, 9, 9, 20],
            route: Routes.tickets,
          ),
          DashKpi(
            icon: PhosphorIconsFill.warningCircle,
            accent: DashColors.red,
            iconBg: DashColors.tintRed,
            value: '3',
            unit: '',
            label: 'SLA Breaches',
            sub: 'Response or resolution',
            trendPositive: true,
            trend: '3.3%',
            arrow: DashTrendArrow.down,
            spark: [5, 5, 4, 4, 4, 3, 3],
            route: Routes.tickets,
          ),
          DashKpi(
            icon: PhosphorIconsFill.timer,
            accent: DashColors.green,
            iconBg: DashColors.tintGreen,
            value: '4.2',
            unit: 'hours',
            label: 'Avg Resolution',
            sub: 'Median, this period',
            trendPositive: true,
            trend: '2.3%',
            arrow: DashTrendArrow.down,
            spark: [5.1, 5, 4.8, 4.7, 4.5, 4.3, 4.2],
            route: Routes.tickets,
          ),
          DashKpi(
            icon: PhosphorIconsFill.lightning,
            accent: DashColors.green,
            iconBg: DashColors.tintGreen,
            value: '8',
            unit: 'min',
            label: 'First Response',
            sub: 'Median, this period',
            trendPositive: true,
            trend: '2.3%',
            arrow: DashTrendArrow.down,
            spark: [11, 10.5, 10, 9.5, 9, 8.4, 8],
            route: Routes.tickets,
          ),
        ],
        helpCategories: [
          DashBar('Complaint', 12),
          DashBar('Request', 8),
          DashBar('Query', 4),
        ],
        helpSla: [
          DashDonutPart('Within SLA', DashColors.green, 15),
          DashDonutPart('At risk', DashColors.amber, 6),
          DashDonutPart('Breached', DashColors.red, 3),
        ],
        helpPriority: [
          DashDonutPart('Urgent', DashColors.red, 3),
          DashDonutPart('High', DashColors.amber, 3),
          DashDonutPart('Medium', DashColors.blue, 9),
          DashDonutPart('Low', DashColors.grey, 9),
        ],
        helpAttention: [
          DashTicketAttn(
              tid: 'TKT-1005',
              subject: 'Escalation: handover delay concern',
              sub: 'Lulu Fashion Store · Manoj, Rahul',
              slaLabel: 'Overdue 9h',
              breached: true,
              paused: false,
              priority: 'Urgent',
              priorityColor: DashColors.red),
          DashTicketAttn(
              tid: 'TKT-1009',
              subject: 'Snag: chipped laminate on counter',
              sub: 'Kalyan Silks · Rahul, Deepak',
              slaLabel: 'Overdue 6h',
              breached: true,
              paused: false,
              priority: 'Medium',
              priorityColor: DashColors.blue),
          DashTicketAttn(
              tid: 'TKT-1008',
              subject: 'Billing query on last invoice',
              sub: 'KIMS Clinic · Manoj',
              slaLabel: 'Overdue 4h',
              breached: true,
              paused: false,
              priority: 'Low',
              priorityColor: DashColors.lowGrey,
          ),
          DashTicketAttn(
              tid: 'TKT-1004',
              subject: 'Clarify AMC coverage scope',
              sub: 'Marari Sands Resort · Arjun',
              slaLabel: 'Respond by 11:30 AM',
              breached: false,
              paused: false,
              priority: 'Low',
              priorityColor: DashColors.lowGrey),
          DashTicketAttn(
              tid: 'TKT-1011',
              subject: 'Signage light flickering',
              sub: 'Lulu Fashion Store · Manoj',
              slaLabel: 'Respond by 12:40 PM',
              breached: false,
              paused: false,
              priority: 'High',
              priorityColor: DashColors.amber),
          DashTicketAttn(
              tid: 'TKT-1015',
              subject: 'Loose wiring at cash counter',
              sub: 'Kalyan Silks · Manoj',
              slaLabel: 'Respond by 1:00 PM',
              breached: false,
              paused: false,
              priority: 'Urgent',
              priorityColor: DashColors.red),
          DashTicketAttn(
              tid: 'TKT-1013',
              subject: 'Water seepage near display window',
              sub: 'Lulu Fashion Store · Deepak',
              slaLabel: 'Respond by 09 Jul, 2:00 PM',
              breached: false,
              paused: false,
              priority: 'High',
              priorityColor: DashColors.amber),
          DashTicketAttn(
              tid: 'TKT-1014',
              subject: 'Replace cracked mirror panel',
              sub: 'Aster Medcity OPD · Anjana',
              slaLabel: 'Respond by 09 Jul, 4:30 PM',
              breached: false,
              paused: false,
              priority: 'Medium',
              priorityColor: DashColors.blue),
          DashTicketAttn(
              tid: 'TKT-1019',
              subject: 'Signage vinyl peeling at entrance',
              sub: 'KIMS Clinic · Manoj',
              slaLabel: 'Respond by 10 Jul, 9:00 AM',
              breached: false,
              paused: false,
              priority: 'Medium',
              priorityColor: DashColors.blue),
          DashTicketAttn(
              tid: 'TKT-1010',
              subject: 'Request revised BOQ for deck furniture',
              sub: 'Marari Sands Resort · Arjun',
              slaLabel: 'Paused',
              breached: false,
              paused: true,
              priority: 'Medium',
              priorityColor: DashColors.blue),
          DashTicketAttn(
              tid: 'TKT-1024',
              subject: 'Confirm veneer shade before rework',
              sub: 'Marari Sands Resort · Manoj',
              slaLabel: 'Paused',
              breached: false,
              paused: true,
              priority: 'Medium',
              priorityColor: DashColors.blue),
        ],
        helpFlow: DashTrend(
          seriesA: [14, 16, 15, 18, 17, 19, 21, 20, 22, 24, 23, 24], // opened
          seriesB: [12, 14, 14, 16, 16, 18, 19, 19, 21, 22, 22, 23], // resolved
          min: 10,
          max: 26,
          axisLabels: ['Jan', 'May', 'Sep', 'Dec'],
        ),
        helpRoster: [
          DashRosterRow('me', '6 open · 3 resolved', '2 breaches', true),
          DashRosterRow('rk', '5 open · 1 resolved', '2 breaches', true),
          DashRosterRow('an', '4 open · 0 resolved', '0 breaches', false),
          DashRosterRow('dr', '4 open · 0 resolved', '1 breach', true),
          DashRosterRow('am', '2 open · 0 resolved', '0 breaches', false),
          DashRosterRow('fa', '1 open · 0 resolved', '0 breaches', false),
        ],

        // ───────────────────────────── Scope ────────────────────────────────
        teamOptions: [
          DashTeamOption('all', 'All teams', 'Everyone in the workspace'),
          DashTeamOption('kochi', 'Team Kochi', 'Kochi metro · 3 members'),
          DashTeamOption('central', 'Team Central', 'Central zone · 1 member'),
          DashTeamOption('north', 'Team North Kerala', 'North zone · 1 member'),
          DashTeamOption('south', 'Team South Kerala', 'South zone · 1 member'),
        ],
      );
}
