import '../../../domain/entities/project.dart';

/// Static project seed — a 1:1 port of the prototype's `PROJ_SEED` array. This
/// is the ONLY place project sample data lives. To integrate the API, replace
/// this class with a remote data source returning `List<Project>`.
class ProjectsMockDataSource {
  const ProjectsMockDataSource();

  List<Project> fetchProjects() => const [
        Project(id: 'PRJ-2401', name: 'Kalyan Silks showroom fit-out', type: 'Fit-out', company: 'Kalyan Silks', internal: false, status: 'active', pri: 'High', progress: 62, manager: 'am', assignees: ['me', 'rk'], myTask: true, start: '02 May 2026', end: '30 Aug 2026', endISO: '2026-08-30', cost: '₹18L', visibility: 'Team', method: 'Task-based', desc: 'Full interior fit-out of the new Kalyan Silks showroom floor — joinery, lighting, trial rooms and façade signage.'),
        Project(id: 'PRJ-2402', name: 'Lulu flagship store interiors', type: 'Fit-out', company: 'Lulu Fashion Store', internal: false, status: 'active', pri: 'High', progress: 41, manager: 'me', assignees: ['rk', 'st'], myTask: false, start: '15 May 2026', end: '20 Sep 2026', endISO: '2026-09-20', cost: '₹36.5L', visibility: 'Team', method: 'Task-based', desc: 'Flagship store fit-out across two floors including MEP coordination and visual merchandising units.'),
        Project(id: 'PRJ-2403', name: 'Marari Sands villa refresh', type: 'Design Services', company: 'Marari Sands Resort', internal: false, status: 'planning', pri: 'Medium', progress: 8, manager: 'an', assignees: ['dr'], myTask: false, start: '01 Aug 2026', end: '30 Nov 2026', endISO: '2026-11-30', cost: '₹22L', visibility: 'Team', method: 'Manual', desc: 'Design refresh for 14 beach villas — interiors, deck furniture and soft furnishing palette.'),
        Project(id: 'PRJ-2404', name: 'Aster Medcity OPD wing', type: 'Fit-out', company: 'Aster Medcity', internal: false, status: 'completed', pri: 'Medium', progress: 100, manager: 'me', assignees: ['am', 'st'], myTask: false, start: '10 Jan 2026', end: '30 May 2026', endISO: '2026-05-30', cost: '₹48L', visibility: 'Team', method: 'Task-based', desc: 'OPD wing interiors — reception, waiting lounges, consult rooms and wayfinding.'),
        Project(id: 'PRJ-2405', name: 'Taj Gateway banquet hall', type: 'Fit-out', company: 'Taj Gateway Annexe', internal: false, status: 'active', pri: 'Medium', progress: 55, manager: 'rk', assignees: ['me'], myTask: true, start: '01 Apr 2026', end: '28 Jun 2026', endISO: '2026-06-28', cost: '₹27L', visibility: 'Team', method: 'Task-based', desc: 'Banquet hall renovation — acoustic panelling, stage, lounge seating and lighting controls.'),
        Project(id: 'PRJ-2406', name: 'Workshop expansion — Aluva unit', type: 'Internal', company: null, internal: true, status: 'planning', pri: 'Low', progress: 15, manager: 'me', assignees: ['fa'], myTask: false, start: '01 Sep 2026', end: '20 Dec 2026', endISO: '2026-12-20', cost: '₹12L', visibility: 'Private', method: 'Manual', desc: 'Expansion of the Aluva joinery workshop — new CNC bay, finishing room and material store.'),
        Project(id: 'PRJ-2407', name: 'Grand Hyatt spa joinery', type: 'Joinery', company: 'Grand Hyatt Kochi', internal: false, status: 'onhold', pri: 'Medium', progress: 34, manager: 'am', assignees: ['dr'], myTask: true, start: '12 Mar 2026', end: '15 Aug 2026', endISO: '2026-08-15', cost: '₹19L', visibility: 'Team', method: 'Task-based', desc: 'Custom teak joinery package for the spa — treatment rooms, relaxation lounge and reception desk.'),
        Project(id: 'PRJ-2408', name: 'Forum Mall kiosks rollout', type: 'Fit-out', company: 'Forum Mall', internal: false, status: 'onhold', pri: 'Low', progress: 20, manager: 'rk', assignees: ['st'], myTask: false, start: '20 Feb 2026', end: '30 Jul 2026', endISO: '2026-07-30', cost: '₹9L', visibility: 'Team', method: 'Manual', desc: 'Rollout of six branded retail kiosks across atrium zones.'),
        Project(id: 'PRJ-2409', name: 'Design studio AMC 2026', type: 'AMC / Maintenance', company: 'Aster Medcity', internal: false, status: 'cancelled', pri: 'Low', progress: 10, manager: 'me', assignees: [], myTask: false, start: '01 Feb 2026', end: '31 Dec 2026', endISO: '2026-12-31', cost: '₹4L', visibility: 'Team', method: 'Manual', desc: 'Annual maintenance contract for completed interior works — descoped after contract revision.'),
        Project(id: 'PRJ-2410', name: 'HQ showroom relighting', type: 'MEP & Services', company: null, internal: true, status: 'completed', pri: 'Low', progress: 100, manager: 'an', assignees: ['rk'], myTask: false, start: '05 Mar 2026', end: '25 Apr 2026', endISO: '2026-04-25', cost: '₹3.5L', visibility: 'Private', method: 'Manual', desc: 'LED relighting of the HQ display showroom with scene presets.'),
      ];
}
